# Site settings
title: Igor APA
email: me@igorapa.com
description: ""
baseurl: ""
url: "http://igorapa.com"
# twitter_username: igorapa
# github_username:  igor-apa

# Build settings
markdown: kramdown
permalink: pretty
