# Site settings
title: Igor APA
email: me@igorapa.com
description: "Sou Front-End Developer e meu intuito com esse site é transmitir o que ando aprendendo, repassando conhecimento."
baseurl: 
paginate: 1
url: http://igorapa.com
permalink: none

author:
name: Igor APA
url: https://twitter.com/igorapa

# Custom vars
repo: https://github.com/igorapa/igorapa.github.io
